#!/bin/bash

WG_DIR=/etc/wireguard

_main () {
    argv0="$1"
    shift

    cmd="$1"
    shift

    case "$cmd" in
        "")
            _usage "${argv0}"
            ;;
        list)
            _list_interfaces
            ;;
        show_conf)
            _show_conf "$@"
            ;;
    esac
}

_usage () {
    echo "$1: CMD"
}

_list_interfaces () {
    local iface

    for iface in $( __list_interfaces ); do
        printf "%s: %d peers\n" "$iface" "$( __iface_count_peers "$iface" )"
    done
}

_show_conf () {
    local iface
    iface="$1"
    peer="$2"
    if [[ -z "$2" ]]; then
        __iface_conf "$iface"
    else
        __peer_remoteconf "$iface" "$peer"
    fi
}

__conf_address_file() {
    local filename
    filename="$1"
    while read -r line; do
        [[ -z "$line" ]] && continue
        [[ "x${line:0:1}" == "x#" ]] && continue
        printf "%s\n" "$line"
    done < "$filename"
}

__peer_dirname () {
    local iface peer
    iface="$1"
    peer="$2"
    printf "%s/peers.d/%s\n" "$(__iface_dirname "$iface")" "$peer"
}

__peer_conf_address () {
    local iface peer ips line
    iface="$1"
    peer="$2"
    __conf_address_file "$( __peer_dirname "$iface" "$peer" )/ip.conf"
}

__peer_conf_networks () {
    local iface peer ips line
    iface="$1"
    peer="$2"
    ips=""
    [[ -e "$(__peer_dirname "$iface" "$peer")/networks.conf" ]] || return
    __conf_address_file "$(__peer_dirname "$iface" "$peer")/networks.conf"
}

__peer_conf_allowedips () {
    local iface peer ips ip
    iface="$1"
    peer="$2"
    ips=""
    for ip in $( __peer_conf_address "$iface" "$peer" ) $( __peer_conf_networks "$iface" "$peer" ); do
        printf -v ips "%s, %s" "$ips" "$ip"
    done
    ips="${ips##, }"
    printf "%s\n" "$ips"
}

__peer_conf_myips () {
    local iface peer ips ip
    iface="$1"
    peer="$2"
    ips=""
    for ip in $( __peer_conf_address "$iface" "$peer" ); do
        printf -v ips "%s, %s" "$ips" "$ip"
    done
    ips="${ips##, }"
    printf "%s\n" "$ips"
}

__peer_conf_publickey () {
    local iface peer pkey line
    iface="$1"
    peer="$2"
    pkey=""
    read -r pkey < "$(__peer_dirname "$iface" "$peer")/public.key"
    printf "%s\n" "$pkey"
}

__peer_conf () {
    local iface peer
    iface="$1"
    peer="$2"
    printf "[Peer] # %s\n" "$peer"
    printf "PublicKey = %s\n" "$( __peer_conf_publickey "$iface" "$peer" )"
    printf "AllowedIPs = %s\n" "$( __peer_conf_allowedips "$iface" "$peer" )"
}

__peer_remoteconf () {
    local iface peer
    iface="$1"
    peer="$2"
    printf "[Interface]\n"
    printf "DNS = 1.1.1.1, 8.8.8.8\n" # FIXME
    printf "Address = %s\n" "$( __peer_conf_myips "$iface" "$peer" )"
    printf "PrivateKey = XXX\n" # FIXME
    printf "# PubKey = YYY\n" # FIXME
    printf "\n"
    printf "[Peer] # %s\n" "$HOSTNAME" # FIXME
    printf "PublicKey = %s\n" "$( __iface_conf_publickey "$iface" )"
    printf "AllowedIPs = %s\n" "$(__iface_conf_allowedips "$iface" )"
    printf "# AllowedIPs = 0.0.0.0/0, ::/0\n" #TODO
    printf "Endpoint = %s:%d\n" "$(__iface_conf_endpoint "$iface")" "$(__iface_conf_listenport "$iface")"
    printf "PersistentKeepalive = 21\n"
    printf "\n"
    printf "# Networks to use:\n"
    for n in $(__peer_conf_networks "$iface" "$peer"); do
        printf "# - %s\n" "$n"
    done
}

__iface_dirname () {
    local iface
    iface="$1"
    printf "%s/%s.conf.d\n" "$WG_DIR" "$iface"
}

__iface_count_peers () {
    local iface peer n
    iface="$1"
    n=0
    for peer in $( __list_peers "$iface" ); do
        n=$(( n + 1 ))
    done
    printf "%d\n" "$n"
}

__iface_conf () {
    local iface
    iface="$1"
    printf "[Interface] # %s\n" "$iface"
    __iface_conf_local "$iface"
    printf "\n"
    __iface_conf_peers "$iface"
    printf "# EOF\n"
}

__iface_conf_local () {
    local iface
    iface="$1"
    printf "Address = %s\n" "$( __iface_conf_address "$iface" )"
    printf "ListenPort = %d\n" "$( __iface_conf_listenport "$iface" )"
    printf "FwMark = %s\n" "$( __iface_conf_fwmark "$iface" )"
    printf "PrivateKey = %s\n" "$( __iface_conf_privatekey "$iface" )"
    printf "# PublicKey = %s\n" "$( __iface_conf_publickey "$iface" )"
    printf "# Local networks:\n"
    for net in $(__iface_conf_networks "$iface" ); do
        printf "# - %s\n" "$net"
    done
}

__iface_conf_address () {
    local iface iface_dirname
    iface="$1"
    iface_dirname="$(__iface_dirname "$iface")"
    ips=""
    while read -r line; do
        printf -v ips "%s, %s" "$ips" "$line"
    done < "${iface_dirname}/ip.conf"
    ips="${ips##, }"
    printf "%s\n" "$ips"
}

__iface_conf_networks () {
    local iface iface_dirname networks network
    iface="$1"
    iface_dirname="$(__iface_dirname "$iface")"
    __conf_address_file "${iface_dirname}/networks.conf"
}

__iface_conf_allowedips () {
    local iface ips ip
    iface="$1"
    ips=""
    for ip in $( __iface_conf_networks "$iface" ); do
        printf -v ips "%s, %s" "$ips" "$ip"
    done
    ips="${ips##, }"
    printf "%s\n" "$ips"
}

__iface_conf_endpoint () {
    local iface endpoint
    iface="$1"
    read -r endpoint < "$(__iface_dirname "$iface" )/endpoint.conf"
    printf "%s\n" "$endpoint"
}

__iface_conf_listenport () {
    printf "%d\n" "51820" # FIXME
}

__iface_conf_fwmark () {
    printf "%s\n" "0xca6c" # FIXME
}

__iface_conf_privatekey () {
    local iface privkey line
    iface="$1"
    privkey=""
    read -r privkey < "$(__iface_dirname "$iface" )/private.key"
    printf "%s\n" "$privkey"
}

__iface_conf_publickey () {
    local iface iface_dirname privkey line
    iface="$1"
    iface_dirname="$(__iface_dirname "$iface")"
    if [[ -e "${iface_dirname}/public.key" ]]; then
        while read -r line; do
            printf "%s\n" "$line"
            break
        done < "${iface_dirname}/public.key"
    else
        wg pubkey < "${iface_dirname}/private.key"
    fi
}

__iface_conf_peers () {
    local iface peer
    iface="$1"
    for peer in $( __list_peers "$iface" ); do
        __peer_conf "$iface" "$peer"
        printf "\n"
    done
}

__list_interfaces () {
    local iface_dirname iface

    for iface_dirname in "$WG_DIR"/*.conf.d; do
        [[ -d "$iface_dirname" ]] || break
        iface="${iface_dirname}"
        iface="${iface##${WG_DIR}/}"
        iface="${iface%%.conf.d}"
        printf "%s\n" "$iface"
    done
}

__list_peers () {
    local iface iface_dirname peer_dirname peer
    iface="$1"
    iface_dirname="$(__iface_dirname "$iface" )"

    for peer_dirname in "${iface_dirname}"/peers.d/*; do
        [[ -d "$peer_dirname" ]] || break
        peer="${peer_dirname}"
        peer="${peer##${iface_dirname}/peers.d/}"
        printf "%s\n" "$peer"
    done
}

set -e

_main "$0" "$@"

